version: '3.8'
services:

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_USER=user1
      - POSTGRES_DB=shareit

  server:
    build: shareit-server
    image: server-image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME:user1
      - SPRING_DATASOURCE_PASSWORD:iamroot

  gateway:
    build: shareit-gateway
    image: gateway-image
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
