DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS item_request CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE if not exists users (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar not null,
  email varchar not null UNIQUE
);

CREATE TABLE if not exists items (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar not null,
  description varchar not null,
  available boolean not null,
  owner_id integer REFERENCES users (id) on delete cascade,
  item_request integer
);

CREATE TABLE if not exists comments (
  id integer generated by default as identity not null PRIMARY KEY,
  text varchar not null,
  item_id integer not null REFERENCES items (id) on delete cascade,
  author_id integer not null REFERENCES users (id) on delete cascade,
  created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE if not exists item_request (
  request_id integer generated by default as identity not null PRIMARY KEY,
  description varchar not null,
  requestor integer REFERENCES users (id) on delete cascade,
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE if not exists bookings (
  id integer generated by default as identity not null PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id integer not null REFERENCES items (id) on delete cascade,
  booker_id integer not null REFERENCES users (id) on delete cascade,
  status varchar
);
